[package]
name = "sudoku-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sudoku-utils = { path = "../", version = "0.1" }
cursive = "0.20"